import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Instalacao',
      collapsed: false,
      items: [
        'instalacao/requisitos',
        'instalacao/desenvolvimento',
        'instalacao/docker',
        'instalacao/variaveis-ambiente',
      ],
    },
    {
      type: 'category',
      label: 'Arquitetura',
      collapsed: false,
      items: [
        'arquitetura/visao-geral',
        'arquitetura/estrutura-projeto',
        'arquitetura/fluxo-dados',
        'arquitetura/multi-tenancy',
        'arquitetura/seguranca',
      ],
    },
    {
      type: 'category',
      label: 'Backend',
      collapsed: true,
      items: [
        'backend/visao-geral',
        'backend/banco-de-dados',
        'backend/services',
        'backend/middlewares',
        'backend/websocket',
        'backend/jobs',
        'backend/utils',
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      collapsed: true,
      items: [
        'frontend/visao-geral',
        'frontend/estrutura',
        'frontend/componentes',
        'frontend/paginas',
        'frontend/stores',
        'frontend/hooks',
        'frontend/estilizacao',
      ],
    },
    {
      type: 'category',
      label: 'Funcionalidades',
      collapsed: true,
      items: [
        'funcionalidades/chat',
        'funcionalidades/tickets',
        'funcionalidades/contatos',
        'funcionalidades/departamentos',
        'funcionalidades/usuarios',
        'funcionalidades/sla-metricas',
        'funcionalidades/base-conhecimento',
        'funcionalidades/faq',
        'funcionalidades/notificacoes',
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      collapsed: true,
      items: [
        'deploy/producao',
        'deploy/nginx',
        'deploy/ssl',
        'deploy/pm2',
        'deploy/monitoramento',
        'deploy/backup',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [
        'troubleshooting/problemas-comuns',
        'troubleshooting/logs',
        'troubleshooting/whatsapp',
        'troubleshooting/banco-dados',
        'troubleshooting/performance',
      ],
    },
  ],

  apiSidebar: [
    'api/introducao',
    {
      type: 'category',
      label: 'Autenticacao',
      collapsed: false,
      items: [
        'api/autenticacao/login',
        'api/autenticacao/registro',
        'api/autenticacao/refresh-token',
        'api/autenticacao/logout',
      ],
    },
    {
      type: 'category',
      label: 'Empresas',
      collapsed: true,
      items: [
        'api/empresas/listar',
        'api/empresas/criar',
        'api/empresas/detalhes',
        'api/empresas/atualizar',
        'api/empresas/configuracoes',
      ],
    },
    {
      type: 'category',
      label: 'Usuarios',
      collapsed: true,
      items: [
        'api/usuarios/listar',
        'api/usuarios/criar',
        'api/usuarios/detalhes',
        'api/usuarios/atualizar',
        'api/usuarios/departamentos',
        'api/usuarios/acesso-empresas',
      ],
    },
    {
      type: 'category',
      label: 'Departamentos',
      collapsed: true,
      items: [
        'api/departamentos/listar',
        'api/departamentos/criar',
        'api/departamentos/detalhes',
        'api/departamentos/atualizar',
        'api/departamentos/usuarios',
      ],
    },
    {
      type: 'category',
      label: 'Conexoes WhatsApp',
      collapsed: true,
      items: [
        'api/conexoes/listar',
        'api/conexoes/criar',
        'api/conexoes/qr-code',
        'api/conexoes/conectar',
        'api/conexoes/desconectar',
        'api/conexoes/webhooks',
        'api/conexoes/listar-templates',
      ],
    },
    {
      type: 'category',
      label: 'Tickets',
      collapsed: true,
      items: [
        'api/tickets/listar',
        'api/tickets/criar',
        'api/tickets/detalhes',
        'api/tickets/status',
        'api/tickets/atribuir',
        'api/tickets/transferir',
        'api/tickets/historico',
      ],
    },
    {
      type: 'category',
      label: 'Mensagens',
      collapsed: true,
      items: [
        'api/mensagens/listar',
        'api/mensagens/enviar-texto',
        'api/mensagens/enviar-midia',
        'api/mensagens/enviar-template',
        'api/mensagens/reagir',
        'api/mensagens/deletar',
      ],
    },
    {
      type: 'category',
      label: 'Contatos',
      collapsed: true,
      items: [
        'api/contatos/listar',
        'api/contatos/detalhes',
        'api/contatos/atualizar',
        'api/contatos/sincronizar-notion',
        'api/contatos/verificar-janela',
      ],
    },
    {
      type: 'category',
      label: 'Metricas',
      collapsed: true,
      items: [
        'api/metricas/dashboard',
        'api/metricas/sla',
        'api/metricas/agentes',
        'api/metricas/departamentos',
      ],
    },
    {
      type: 'category',
      label: 'Base de Conhecimento',
      collapsed: true,
      items: [
        'api/conhecimento/listar',
        'api/conhecimento/criar',
        'api/conhecimento/atualizar',
        'api/conhecimento/deletar',
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsed: true,
      items: [
        'api/faq/listar',
        'api/faq/criar',
        'api/faq/atualizar',
        'api/faq/deletar',
      ],
    },
    {
      type: 'category',
      label: 'Upload',
      collapsed: true,
      items: [
        'api/upload/arquivo',
      ],
    },
    {
      type: 'category',
      label: 'WebSocket',
      collapsed: true,
      items: [
        'api/websocket/eventos',
        'api/websocket/rooms',
        'api/websocket/mensagens',
      ],
    },
  ],

  trainingSidebar: [
    'treinamento/introducao',
    {
      type: 'category',
      label: 'Manual do Atendente',
      collapsed: false,
      items: [
        'treinamento/atendente/primeiros-passos',
        'treinamento/atendente/interface-chat',
        'treinamento/atendente/enviando-mensagens',
        'treinamento/atendente/gerenciando-tickets',
        'treinamento/atendente/trabalhando-com-ia',
      ],
    },
    {
      type: 'category',
      label: 'Manual do Supervisor',
      collapsed: true,
      items: [
        'treinamento/supervisor/visao-geral',
        'treinamento/supervisor/dashboard',
        'treinamento/supervisor/gestao-equipe',
        'treinamento/supervisor/sla-qualidade',
        'treinamento/supervisor/relatorios',
      ],
    },
    {
      type: 'category',
      label: 'Manual do Administrador',
      collapsed: true,
      items: [
        'treinamento/administrador/painel-controle',
        'treinamento/administrador/configurando-whatsapp',
        'treinamento/administrador/usuarios-departamentos',
        'treinamento/administrador/configuracoes-avancadas',
        'treinamento/administrador/integracoes',
      ],
    },
    {
      type: 'category',
      label: 'Configurando a IA',
      collapsed: true,
      items: [
        'treinamento/ia/configuracao-basica',
        'treinamento/ia/escolhendo-provedor',
        'treinamento/ia/personalidade',
        'treinamento/ia/base-conhecimento',
        'treinamento/ia/ajuste-fino',
      ],
    },
    {
      type: 'category',
      label: 'Boas Praticas',
      collapsed: true,
      items: [
        'treinamento/boas-praticas/comunicacao',
        'treinamento/boas-praticas/eficiencia',
        'treinamento/boas-praticas/qualidade',
        'treinamento/boas-praticas/seguranca',
      ],
    },
    'treinamento/faq',
    'treinamento/glossario',
  ],

  guidesSidebar: [
    'guias/introducao',
    {
      type: 'category',
      label: 'WhatsApp',
      collapsed: false,
      items: [
        'guias/whatsapp/configuracao',
        'guias/whatsapp/baileys',
        'guias/whatsapp/meta-cloud-api',
        'guias/whatsapp/templates',
        'guias/whatsapp/midia',
      ],
    },
    {
      type: 'category',
      label: 'Inteligencia Artificial',
      collapsed: false,
      items: [
        'guias/inteligencia-artificial/configuracao',
        'guias/inteligencia-artificial/openai',
        'guias/inteligencia-artificial/anthropic',
        'guias/inteligencia-artificial/personalidade',
        'guias/inteligencia-artificial/transcricao',
        'guias/inteligencia-artificial/transferencia',
      ],
    },
    {
      type: 'category',
      label: 'Notion',
      collapsed: true,
      items: [
        'guias/notion/configuracao',
        'guias/notion/sincronizacao',
        'guias/notion/mapeamento-campos',
      ],
    },
    {
      type: 'category',
      label: 'SLA',
      collapsed: true,
      items: [
        'guias/sla/configuracao',
        'guias/sla/alertas',
        'guias/sla/relatorios',
      ],
    },
    {
      type: 'category',
      label: 'Administracao',
      collapsed: true,
      items: [
        'guias/administracao/empresas',
        'guias/administracao/usuarios',
        'guias/administracao/departamentos',
        'guias/administracao/permissoes',
      ],
    },
  ],
};

export default sidebars;
